### ISSUE TITLE
Setting subscription name using `spring.pulsar.consumer.subscription.name` configuration property doesn't work

### ISSUE THREAD

**Issue by vpavic** [spring-projects/spring-pulsar#480]
[Pulsar Listener section](https://docs.spring.io/spring-pulsar/docs/1.0.0-RC1/reference/reference/pulsar.html#pulsar-listener) of reference manual provides snippets that suggest it's possible to configure subscription name only using `spring.pulsar.consumer.subscription.name` configuration property and without having `subscriptionName` specified on `@PulsarListener`.

However, in practice, I don't see this being possible due to subscription name being generated in `PulsarListenerAnnotationBeanPostProcessor` if omitted on annotation:
https://github.com/spring-projects/spring-pulsar/blob/728a74bcb00c6ee5b884ea8641c48fd309240240/spring-pulsar/src/main/java/org/springframework/pulsar/annotation/PulsarListenerAnnotationBeanPostProcessor.java#L364-L369

Which combined with `DefaultPulsarConsumerFactory` applying the generated subscription name to `ConsumerBuilder` results in the value specified by `spring.pulsar.consumer.subscription.name` configuration property being overwritten by generated one:
https://github.com/spring-projects/spring-pulsar/blob/728a74bcb00c6ee5b884ea8641c48fd309240240/spring-pulsar/src/main/java/org/springframework/pulsar/core/DefaultPulsarConsumerFactory.java#L86-L88

**Comment by onobc** [comment]
Hi @vpavic - thanks for the report, I will take a look.

**Comment by onobc** [comment]
Good catch @vpavic, you are correct. This does not work as advertised because (as you detailed in the description) the default is only applied if the incoming name is null and in this case the annotation processor has set it to the generated name.

That being said, I don't think it would be valuable to use the default sub name because it is likely there will be multiple `@PulsarListener`s which would then require separate names. What I think would be helpful would be to allow the setting a default listener container sub name generated prefix and then the name would be `MY_PREFIX(0...N)`. A more flexible step would be to introduce the concept of a subscription name generator and plug that into the listener/containers. 

For now I will remove the falsey out of the docs and keep this issue open for further exploration around this area. Sound good to you? 

Again, thanks for finding this and thanks for the detailed analysis.

**Comment by vpavic** [comment]
Thanks for looking into this @onobc, I'll review the PR that updates the documentation.

To give you more context about our use case - we're integrating with a 3rd party platform that exposes Pulsar-based message queue that is used to subscribe to events that occur within that platform. So we'll only have a single `@PulsarListener` where subscription name is based on our tenant id (the actual pattern is `${tenantId}-sub`) and therefore should be externally configurable (because tenant ids will differ from environment to environment).

That's why the originally documented combination of `@PulsarListener` without subscription name coupled with `spring.pulsar.consumer.subscription.name` would be ideal for our use case.

I should note that there are also some workarounds possible, such as `@PulsarListener(subscriptionName = "${spring.pulsar.consumer.subscription.name}")` - this is not pretty but it works around the issue and allows subscription name to be managed using properties.

Other solution is to use `ConsumerBuilderCustomizer` and supply subscription name there, but this still needs the customizer to be referred to from the annotation `@PulsarListener(consumerCustomizer = "myConsumerBuilderCustomizer")`. This approach is actually quite similar to _the concept of a subscription name generator_ that you mentioned. The only improvement I'd like to see is that if there's only one `ConsumerBuilderCustomizer` bean available in the context it could be applied implicitly, without the need to refer to it in `@PulsarListener`.

**Comment by onobc** [comment]
> That's why the originally documented combination of @PulsarListener without subscription name coupled with spring.pulsar.consumer.subscription.name would be ideal for our use case.

Ahh, good to know this use case. 

> I should note that there are also some workarounds possible, such as @PulsarListener(subscriptionName = "${spring.pulsar.consumer.subscription.name}") 

Ha! I was going to point to this workaround now as well. I would go w/ this one over the customizer for your particular case. 

> The only improvement I'd like to see is that if there's only one ConsumerBuilderCustomizer bean available in the context it could be applied implicitly, without the need to refer to it in @PulsarListener.

Also, what if there are multiple PulsarListeners - would we want to auto-apply the single customizer to all PLs? Either way, I could see some users not wanting the auto-apply in this case. This would lead us to having a switch to disable the auto-apply. 

I might introduce the subscriptionName generator concept and auto-apply it to all listeners if it is provided in the context otherwise go w/ the default generator. This will be low risk (additive) and will solve your case.

**Comment by vpavic** [comment]
I understand the reasoning for not auto-applying `ConsumerBuilderCustomizer`.

> I might introduce the subscriptionName generator concept and auto-apply it to all listeners if it is provided in the context otherwise go w/ the default generator. This will be low risk (additive) and will solve your case.

This sounds good to me. I you decide that you definitely want to go this route, I'd be willing to contribute.

**Comment by onobc** [comment]
> I'd be willing to contribute.

I wish I would have checked this comment a few hours ago as I am about 95% done w/ implementing it :) 

I will add tests later today or tomorrow and then submit the PR and you can code review it if you don't mind.

**Comment by vpavic** [comment]
No worries, if you were able to work on this immediately it's probably better that way because it would take at least a week or so for me to find time to dedicate to this.

There will be time for other contributions I'm sure, as this 3rd party platform that we're integrating with over Pulsar is quite a substantial part of one of our current projects. :slightly_smiling_face:

Anyway, feel free to ping me when you have the PR ready, I'll be glad to take a look.

**Comment by vpavic** [comment]
@onobc I've just realized that a similar problem to this happens also affects other properties - for now I know that `spring.pulsar.consumer.subscription.type` is affected. I'll open a separate issue shortly with some details.

In the meanwhile, maybe #483 should be put on-hold until the overall situation with configuring consumer using configuration properties is assessed.

**Comment by onobc** [comment]
Will take a look at the other properties when you file the issue. We have limited time to get this in so if we can adjust to include the type then we will try to include them. Otherwise, having the ability to generate the subscription name would be valuable w/ or w/o the other properties IMO.

**Comment by vpavic** [comment]
I've opened #488.

My point is that the usability of subscription name generator is reduced due to other consumer properties also being impacted, which suggest that `ConsumerBuilderCustomizer` is a more robust mechanism for such customizations.

**Comment by onobc** [comment]
Thanks @vpavic ,

> which suggest that ConsumerBuilderCustomizer is a more robust mechanism for such customizations.

Sure, we could do whatever in the customizer but the point of the generator was so that one would not have to set the customizer on each and every listener (your use case for example). 

Let's continue the discussion on the other ticket. I commented w/ some options.

**Comment by onobc** [comment]
Hi @vpavic ,
I think w/ the introduction of the `PulsarListenerConsumerBuilderCustomizer` making it auto-associate w/ the PulsarListener when there is only 1 customizer and 1 listener in the context will be simple which would allow us to use the customizer instead of the name generator. I should have a PR for this in the next 24hrs.

**Comment by onobc** [comment]
Closed via 
https://github.com/spring-projects/spring-pulsar/commit/836d385d8696f28f1229ade22efd3fa6adf15720.

To customize the subscription name, use a customizer as shown below. Also note that when there is only a single listener and a single customizer that it will be automatically applied:

```java
@PulsarListener(topics = "my-topic")
void listen(String msg) {
	...
}

@Bean
PulsarListenerConsumerBuilderCustomizer<String> myCustomizer() {
	return (builder) -> builder.subscriptionName("FOO");
}

```

**Comment by onobc** [comment]
Closing via https://github.com/spring-projects/spring-pulsar/commit/836d385d8696f28f1229ade22efd3fa6adf15720.
