### ISSUE TITLE
[question] why do we have to create partition producer everytime

### ISSUE THREAD

**Issue by chenliang7558** [spring-projects/spring-pulsar#806]
- version:
>  <dependency>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-pulsar</artifactId>
        <version>3.2.8</version>
      </dependency>
- code:
```yaml
spring:
  pulsar:
    client:
      serviceUrl: pulsar://pulsar.dev.com:6650
```
**producer** 
```java
@Component
@RequiredArgsConstructor
public class ProducerExample implements CommandLineRunner {

    private final PulsarTemplate pulsarTemplate;

    private final TraceProducerInterceptor traceProducerInterceptor;

    public void sendOne() throws PulsarClientException {
        String msg = "hello world";
        pulsarTemplate.newMessage(msg)
                .withTopic("persistent://test/test/topic-test")
                .withProducerCustomizer((pb) -> pb.intercept(traceProducerInterceptor)).send();
    }


    @Override
    public void run(String... args) throws Exception {
        ScheduledExecutorService executor = Executors.newScheduledThreadPool(1);
        executor.scheduleAtFixedRate(() -> {
            try {
                sendOne();
            } catch (PulsarClientException e) {
                throw new RuntimeException(e);
            }
        }, 5, 5, TimeUnit.SECONDS);
    }
}

```
- performance
**log** 
![image](https://github.com/user-attachments/assets/aa6ec56c-584f-473e-a4e7-418bf76fce9f)
- source code

![image](https://github.com/user-attachments/assets/d191881e-4cde-4ff6-8c80-4301ca6ac85a)

- quesion: Why not use map to store all clients like Pulsar client, instead of creating it every time it is sent

**Comment by onobc** [comment]
Hi @chenliang7558 ,

By **default**, the `PulsarTemplate` is [configured w/ a caching producer factory](https://docs.spring.io/spring-pulsar/reference/reference/pulsar/message-production.html#producer-caching) that caches and [returns proxies around the actual created producer](https://github.com/spring-projects/spring-pulsar/blob/eefea9af69c92cea8e943433f4f11edaf08330a0/spring-pulsar/src/main/java/org/springframework/pulsar/core/CachingPulsarProducerFactory.java#L114) that do not actually close the producers.

**However**, in your case the issue is that the cache is missing due the [limitations of lambdas being used](https://docs.spring.io/spring-pulsar/reference/reference/pulsar/message-production.html#producer-caching-lambdas) as part of the producer cache key. The above linked doc section is a bit confusing but the rule summary can be found:
> [!IMPORTANT]
> RULE: If your Lambda customizer is not defined once and only once (the same instance is used on subsequent calls) OR it requires variable(s) defined outside its closure then you must provide a customizer implementation with a valid equals/hashCode implementation.

And **in your case**, it is because the lambda uses a variable defined **outside** **its** **closure**. 

This issue was originally reported here https://github.com/spring-projects/spring-pulsar/issues/593#issuecomment-1970105027 in relation to interceptors. 

## Options

### Customizer impl w/ eq/hc
One option is to create a customizer impl w/ valid eq/hc and use that instead of using a lambda. I know, not ideal, but you can use a record as it implements eq/hc and just implement customizer interface, something like:
```java
record TraceProducerInterceptorCustomizer(TraceProducerInterceptor traceInterceptor) implements ProducerBuilderCustomizer<String> {

	@Override
	public void customize(ProducerBuilder<String> producerBuilder) {
		producerBuilder.intercept(traceInterceptor);
	}

}
```

#### Producer interceptor bean
Another option, if it is ok for this interceptor to be applied to all template send operations then you could [define a ProducerInterceptor bean](https://docs.spring.io/spring-pulsar/reference/reference/pulsar/message-production.html#_intercept_messages_on_the_producer)  - you may not want this coarse grained behavior though.

I hope this helps - please let us know how it goes.

**Comment by chenliang7558** [comment]
@onobc thanks you very much！ I used option one and it worked normally.
